import {auth,db,firebaseConfigured,onAuthStateChanged,doc,getDocFromServer,getDocsFromServer,collection,query,orderBy,limit,where,startAfter,setDoc,serverTimestamp} from './firebase-client.js?v=54-member-nav';
import {summarize,dayBefore} from './dev-metrics.js?v=56';
import {gymDate,money} from './billing-model.js?v=54-member-nav';
const $=s=>document.querySelector(s);let epoch=0,authorized=null,busy=false;
function el(tag,text){const node=document.createElement(tag);node.textContent=text;return node;}
function table(target,headers,rows){const host=$(target);host.replaceChildren();if(!rows.length){host.append(el('p','No findings in the loaded records.'));return;}const wrap=el('div','');wrap.className='table-wrap';const t=el('table',''),head=el('thead',''),hr=el('tr','');headers.forEach(h=>hr.append(el('th',h)));head.append(hr);t.append(head);const body=el('tbody','');rows.slice(0,150).forEach(row=>{const tr=el('tr','');row.forEach(v=>tr.append(el('td',String(v??''))));body.append(tr)});t.append(body);wrap.append(t);host.append(wrap);if(rows.length>150)host.append(el('p','Showing first 150 findings. Open the owner roster to review the rest.'));}
function tile(id,value,note,tone){const n=$(id);n.className='tile '+tone;n.querySelector('strong').textContent=value;n.querySelector('small').textContent=note;}
function allowed(token){return authorized&&auth.currentUser?.uid===authorized.uid&&token===epoch;}
const timeout=p=>{let timer;return Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Request timed out')),15000)})]).finally(()=>clearTimeout(timer));};
async function readList(name,sort,max,pages=1,constraints=[]){let rows=[],cursor=null,truncated=false;for(let i=0;i<pages;i++){const q=query(collection(db,name),...(sort?[orderBy(sort,'desc')]:[]),...constraints,...(cursor?[startAfter(cursor)]:[]),limit(max));const snap=await timeout(getDocsFromServer(q));rows.push(...snap.docs.map(d=>({...d.data(),id:d.id})));if(snap.docs.length<max)return {rows,truncated:false};cursor=snap.docs.at(-1);truncated=true;}return {rows,truncated};}
function unavailable(target){$(target).replaceChildren(el('p','Unavailable—this source did not load. Refresh to retry.'));}
function renderData(results){const data={};for(const [k,v]of Object.entries(results))data[k]=v?.rows||[];const m=summarize(data);const has=k=>!!results[k];
 const alerts=[];
 if(has('members')&&has('billing')){
  tile('#billing-tile',`${m.due.length} payment due`,`${money(m.dueCents)} estimated dues to review` ,m.due.length?'warn':'good');
  $('#billing-summary').textContent=`${m.active.length} active · ${m.roster.length-m.active.length} inactive · ${data.members.filter(x=>x.archived).length} archived. ${m.locked.length} current/exempt but access disabled. ${has('attendance')?m.unpaidVisits.length+' currently unpaid with visits in the last 30 days.':'Attendance unavailable.'}`;
  table('#billing-list',['Member','Finding'],[...m.due.map(x=>[x.name||x.email,'Payment due']),...m.locked.map(x=>[x.name||x.email,'Current/exempt, but inactive or portal disabled']),...(has('attendance')?m.unpaidVisits.map(x=>[x.name||x.email,'Current dues unpaid; recent recorded visit']):[])]);
  if(m.due.length)alerts.push(`${m.due.length} members need payment review (${money(m.dueCents)} estimated dues).`);
  if(m.locked.length)alerts.push(`${m.locked.length} current/exempt accounts have disabled access. Review intentional holds.`);
 }else{tile('#billing-tile','Unavailable','Roster or billing read failed','bad');unavailable('#billing-list');$('#billing-summary').textContent='';}
 if(has('members')){
  $('#quality-summary').textContent=`${m.missing.length} missing required waivers · ${m.exempt} exempt. ${m.quality.length} quality findings${has('attendance')?'':'; attendance source unavailable'}.`;
  table('#quality-list',['Member / record','Finding'],[...m.missing.map(x=>[x.name||x.email,'Required waiver missing']),...m.quality.map(x=>[x.name,x.issue])]);
  if(m.missing.length)alerts.push(`${m.missing.length} members are missing a required waiver.`);
  if(m.quality.length)alerts.push(`${m.quality.length} data-quality findings need review.`);
 }else{unavailable('#quality-list');$('#quality-summary').textContent='';}
 if(has('members')&&has('attendance')){
  $('#engagement-summary').textContent=`${m.current} check-ins / last 30 days vs ${m.previous} / previous 30. ${m.newCurrent} joined in the last 30 days vs ${m.newPrevious} previously.${has('payments')?' Recorded payments: '+money(m.collected)+' vs '+money(m.collectedPrevious)+'.':''}${has('trials')?' '+m.converted+' of '+m.trialCount+' loaded trial email addresses match a member (not trial-to-paid conversion).':''}`;
  const bars=$('#attendance-bars');bars.replaceChildren();const max=Math.max(1,...m.week.map(d=>d.count));for(const d of m.week){const col=el('div','');col.className='bar';col.append(el('b',d.count));const bar=el('i','');bar.style.height=Math.max(2,d.count/max*110)+'px';col.append(bar,el('small',d.date.slice(5)));bars.append(col)}
  table('#risk-list',['Member','Last recorded visit','Review'],m.atRisk.map(x=>[x.name,x.last,x.band]));
  table('#cohorts',['Joined month','Stored members','Active now'],m.cohorts.map(x=>[x.month,x.total,x.active]));
  $('#cohorts').append(el('p','Current active status by join month; deleted members are unavailable. This is not historical churn.'));
  if(m.atRisk.length)alerts.push(`${m.atRisk.length} active members have no recent recorded attendance or an unknown join date.`);
 }else{unavailable('#risk-list');unavailable('#cohorts');$('#attendance-bars').replaceChildren();$('#engagement-summary').textContent='Roster or attendance unavailable; engagement metrics withheld.';}
 const host=$('#attention');host.replaceChildren();for(const text of alerts){const node=el('div',text);node.className='alert';host.append(node)}if(!alerts.length)host.append(el('p',Object.values(results).some(v=>!v)?'Some checks are unavailable; review source status below.':'No roster/billing/attendance findings in the loaded records. Check the exceptions panel below.'));
 if(results.errors){const open=results.errors.rows.filter(x=>x.status!=='resolved');if(open.length){const node=el('div',`${open.length} open exception slots. Expand Exceptions & recovery below.`);node.className='alert';host.prepend(node)}}
}
async function probe(){const start=performance.now();const response=await fetch('index.html?health='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error('HTTP '+response.status);return Math.round(performance.now()-start);}
function showOps(data){for(const [id,key]of [['backup-date','backupDate'],['restore-date','restoreDate'],['domain-date','domainDate'],['ops-note','note']])$('#'+id).value=data?.[key]||'';const today=gymDate();const stale=!data?.backupDate||data.backupDate<dayBefore(today,7);tile('#backup-tile',data?.backupDate||'Unverified',data?.restoreDate?'Restore test recorded '+data.restoreDate:'No restore test recorded',stale||!data?.restoreDate?'warn':'good');$('#ops-status').textContent=(data?.updatedBy?'Last recorded by '+data.updatedBy+'. Manually reported; not independently verified. ':'')+(data?.domainDate&&data.domainDate<=dayBefore(today,-30)?'Domain renewal date is due or within 30 days.':'');}
async function refresh(){if(!authorized||busy)return;busy=true;const token=epoch;$('#refresh').disabled=true;$('#snapshot').textContent='Checking sources…';const start=performance.now();
 const requests={members:()=>readList('members',null,250,4),billing:()=>readList('billingProfiles',null,250,4),attendance:()=>readList('attendance','classDate',500,1,[where('classDate','>=',dayBefore(gymDate(),59))]),payments:()=>readList('payments','paidOn',250,1,[where('paidOn','>=',dayBefore(gymDate(),59))]),trials:()=>readList('trialWaivers',null,250),errors:()=>readList('clientDiagnostics','updatedAt',100),ops:()=>timeout(getDocFromServer(doc(db,'developerOperations','current'))),releases:()=>readList('developerReleases','createdAt',30),site:probe};
 const keys=Object.keys(requests);const outcomes=await Promise.allSettled(keys.map(k=>requests[k]()));if(!allowed(token))return;
 const result={};const statuses=[];outcomes.forEach((r,i)=>{const k=keys[i];result[k]=r.status==='fulfilled'?r.value:null;statuses.push(`${k}: ${r.status==='fulfilled'?(r.value.truncated?'limit reached—partial':r.value.rows?r.value.rows.length+' loaded':'checked'):'unavailable'}`)});
 renderData(result);showOps(result.ops?.exists()?result.ops.data():null);if(!result.ops)$('#ops-status').textContent='Operations record unavailable; do not assume no backup exists.';
 table('#releases',['Recorded deployment','Build','Note'],(result.releases?.rows||[]).map(x=>[x.createdAt?.toDate?.().toLocaleString()||'Pending timestamp',x.build,x.note]));if(!result.releases)unavailable('#releases');
 tile('#site-tile',result.site!==null&&result.members?'Reachable':'Needs review',result.site!==null?`Homepage ${result.site} ms · refresh ${Math.round(performance.now()-start)} ms. One browser check.`:'Homepage probe failed; not a global outage verdict.',result.site!==null&&result.members?'good':'bad');
 $('#snapshot').textContent=`Checked ${new Date().toLocaleString()} · manual snapshot\n${statuses.join(' · ')}\nCapped sources are partial; their counts are lower bounds and trends are incomplete. No continuous uptime or full-funnel tracking.`;
 window.RRDiagnostics?.showAdmin(true);$('#diagnostics-refresh').click();busy=false;$('#refresh').disabled=false;
}
const coverage=[['Available now','Server reads, browser homepage latency, manual billing/access review, required waivers, recent attendance, data quality, sanitized exceptions.'],['Exceptions scope','Latest 100 report slots; max 10 slots per verified account. Counts are session occurrences, not an error rate. No raw stack traces or member form contents.'],['Not connected','External uptime/HTTP error-rate monitoring, SSL expiry, email/SMS delivery, automated backups, alert delivery, historical usage and signup funnel.'],['Not used by this site','Stripe/card retries, processor webhooks, disputes, bookings/capacity/waitlists, video library and subscription cancellation reasons.'],['Security limits','No IP collection or global failed-login history. Developer access is verified before reads; Firestore enforces the underlying permissions.'],['Data scope','Up to 1,000 members and billing profiles, 500 attendance rows / 60 days, 250 payments / 60 days, 250 trials. Refresh does not write member data.']];
table('#coverage',['Coverage','Meaning'],coverage);
$('#refresh').addEventListener('click',()=>refresh().catch(()=>{busy=false;$('#refresh').disabled=!authorized;$('#snapshot').textContent='Refresh failed. Retry; no healthy state is implied.'}));
$('#ops-form').addEventListener('submit',async event=>{event.preventDefault();if(!authorized)return;const token=epoch,button=event.submitter;button.disabled=true;try{const data={backupDate:$('#backup-date').value,restoreDate:$('#restore-date').value,domainDate:$('#domain-date').value,note:$('#ops-note').value.trim(),updatedBy:authorized.email.toLowerCase(),updatedAt:serverTimestamp()};if(data.backupDate>gymDate()||data.restoreDate>gymDate())throw Error('Backup and restore dates cannot be in the future.');await setDoc(doc(db,'developerOperations','current'),data);if(allowed(token)){showOps(data);$('#ops-status').textContent='Saved manual operations record.'}}catch(error){if(allowed(token))$('#ops-status').textContent=error.message?.startsWith('Backup')?error.message:'Could not save. Check connection and deployed rules.'}finally{button.disabled=false}});
$('#release-form').addEventListener('submit',async event=>{event.preventDefault();if(!authorized)return;const token=epoch,button=event.submitter;button.disabled=true;try{await setDoc(doc(db,'developerReleases',crypto.randomUUID()),{build:$('#release-build').value.trim(),note:$('#release-note').value.trim(),createdBy:authorized.email.toLowerCase(),createdAt:serverTimestamp()});if(allowed(token)){$('#release-status').textContent='Deployment recorded. This does not deploy the website.';await refresh()}}catch(_){if(allowed(token))$('#release-status').textContent='Could not record deployment. Check connection and rules.'}finally{button.disabled=false}});
if(!firebaseConfigured||!auth){$('#gate').textContent='Firebase is not configured.';}else onAuthStateChanged(auth,async user=>{const token=++epoch;authorized=null;busy=false;$('#console').hidden=true;$('#refresh').disabled=true;window.RRDiagnostics?.showAdmin(false);for(const id of ['#billing-summary','#billing-list','#quality-summary','#quality-list','#engagement-summary','#attendance-bars','#risk-list','#cohorts','#attention','#releases','#snapshot'])$(id).replaceChildren();$('#ops-form').reset();$('#release-form').reset();
 if(!user||user.isAnonymous||!user.emailVerified){$('#gate').replaceChildren(el('span','Verified developer sign-in required. '));const a=el('a','Sign in');a.href='members.html';$('#gate').append(a);return;}
 try{const role=await timeout(getDocFromServer(doc(db,'developers',user.email.toLowerCase())));if(token!==epoch||auth.currentUser?.uid!==user.uid)return;if(!role.exists()||role.data().enabled!==true){$('#gate').textContent='Developer access required. Owners and coaches use the owner dashboard.';return;}authorized=user;$('#gate').textContent='Verified developer session · private operational data';$('#console').hidden=false;$('#refresh').disabled=false;await refresh();}catch(_){if(token===epoch)$('#gate').textContent='Developer access could not be verified. Reconnect and reload.'}
});
