import {auth,db,firebaseConfigured,onAuthStateChanged,doc,getDocFromServer,getDocsFromServer,collection,query,where,limit} from './firebase-client.js?v=54-member-nav';
import {myChildren,childLogin,checkInChild,normalize} from './family-store.js?v=59';
import {currentClass,checkInNotice} from './class-schedule.js?v=54-member-nav';
import {attachWaiverPrint} from './waiver-pdf.js?v=54-member-nav';
const $=s=>document.querySelector(s),make=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};let generation=0,session=null,childOnly=false;
function valid(epoch){return epoch===generation&&session?.uid===auth.currentUser?.uid;}
async function loadFamily(){if(!session)return;const epoch=generation;$('#refresh-family').disabled=true;$('#family-gate').textContent='Loading family profiles…';
 try{let children;const link=await childLogin(session.email);if(!valid(epoch))return;childOnly=!!link;if(link){const snap=await getDocFromServer(doc(db,'children',link.childId));children=snap.exists()?[{...snap.data(),id:snap.id}]:[];}else children=await myChildren(session);if(!valid(epoch))return;$('#add-child').hidden=childOnly;$('#family-intro').textContent=childOnly?'Your own rank and attendance. Check in during Kids class hours.':'One profile per child. Staff confirm family coverage before check-in is enabled. No separate child charge is added here.';$('#children-list').replaceChildren();
 for(const child of children){const card=make('article','');card.className='child-card';card.append(make('h3',child.name),make('p',`${child.plan} · ${child.rank} · ${child.stripes} stripes`),make('p',child.status==='active'?`Family-covered · $0 additional · Payer: ${child.payerEmail}`:child.status==='pending'?'Waiver saved · Waiting for staff to confirm family coverage.':'Profile paused. Contact staff before training.'));
 if(child.loginEmail&&!childOnly)card.append(make('p',`Own-phone login approved: ${child.loginEmail}. Use Set Up Account with that email; no second enrollment is needed.`));
 const actions=make('div','');actions.className='family-actions';const status=make('p','');status.className='child-actions-status';status.setAttribute('role','status');
 const check=make('button','Check In — Kids Class');check.className='btn btn-red';check.type='button';check.disabled=child.status!=='active'||!currentClass({plan:'Kids'});check.addEventListener('click',async()=>{check.disabled=true;try{const fresh=await checkInChild(child);if(!valid(epoch))return;status.textContent=fresh?'Checked in.':'Already checked in for this class.';}catch(e){if(valid(epoch)){status.textContent=e.message?.startsWith('Kids check-in')?e.message:'Check-in could not be confirmed. Refresh before retrying.';check.disabled=false;}}});
 const waiver=make('button','View Signed Waiver');waiver.className='btn btn-dark';waiver.type='button';const print=make('div','');waiver.addEventListener('click',async()=>{waiver.disabled=true;try{const snap=await getDocFromServer(doc(db,'childWaivers',child.id));if(!valid(epoch))return;if(!snap.exists())throw Error();print.replaceChildren();attachWaiverPrint(snap.data(),print);}catch(_){if(valid(epoch))status.textContent='Waiver could not load. Please retry.'}finally{waiver.disabled=false}});
 const history=make('button','Attendance');history.type='button';history.className='btn btn-dark';const historyList=make('div','');history.addEventListener('click',async()=>{history.disabled=true;try{const snap=await getDocsFromServer(query(collection(db,'attendance'),where('childId','==',child.id),limit(250)));if(!valid(epoch))return;const rows=snap.docs.map(d=>d.data()).sort((a,b)=>b.classDate.localeCompare(a.classDate));historyList.replaceChildren(make('p',`${rows.length}${rows.length===250?'+ (limit reached)':''} recorded classes loaded`));const list=make('ul','');rows.forEach(row=>list.append(make('li',row.classDate+' · '+row.className)));historyList.append(list);}catch(_){if(valid(epoch))status.textContent='Attendance could not load. Please retry.'}finally{history.disabled=false}});
 actions.append(check,history,waiver);card.append(make('p',checkInNotice({plan:'Kids'})),actions,status,historyList,print);$('#children-list').append(card);}
 if(!children.length)$('#children-list').append(make('p','Start with Add My Child. Each child gets a separate waiver, rank and attendance record.'));$('#family-gate').textContent='Signed in as '+session.email;
 }catch(_){if(valid(epoch))$('#family-gate').textContent='Family profiles could not load. Check your connection and ask staff to confirm the new rules were published.';}finally{if(valid(epoch))$('#refresh-family').disabled=false;}}
$('#add-child').onclick=()=>{$('#child-form-panel').hidden=false;$('#child-name').focus();};$('#cancel-child').onclick=()=>{$('#child-form-panel').hidden=true;};$('#refresh-family').onclick=loadFamily;
$('#child-form').onsubmit=async event=>{event.preventDefault();if(!session||childOnly)return;const dob=$('#child-dob').value,birth=new Date(dob+'T12:00:00'),now=new Date();let age=now.getFullYear()-birth.getFullYear();if(now.getMonth()<birth.getMonth()||(now.getMonth()===birth.getMonth()&&now.getDate()<birth.getDate()))age--;if(!Number.isFinite(age)||age<0||age>=18){$('#child-form-status').textContent='Use this form for children under 18.';return;}const loginEmail=normalize($('#child-login-email').value);if(loginEmail===normalize(session.email)){$('#child-form-status').textContent='Leave the child login blank when using your own account.';return;}try{sessionStorage.setItem('redroad:pendingChild',JSON.stringify({name:$('#child-name').value.trim(),dob,loginEmail,guardianUid:session.uid}));location.assign('waiver.html?child=1');}catch(_){$('#child-form-status').textContent='Allow tab storage before continuing.';}};
if(!firebaseConfigured||!auth)$('#family-gate').textContent='Sign-in is unavailable.';else onAuthStateChanged(auth,user=>{generation++;session=user&&!user.isAnonymous&&user.emailVerified?user:null;$('#children-list').replaceChildren();$('#child-form').reset();$('#child-form-panel').hidden=true;$('#family-app').hidden=!session;$('#family-login').hidden=!!session;$('#family-gate').textContent=session?'Loading…':'Sign in with your verified parent account to continue.';if(session)void loadFamily();});
